apiVersion: v1
kind: List
items:
- apiVersion: enmasse.io/v1alpha1
  kind: Address
  metadata:
    name: user1-fuse-space.my-queue 
    # Address space and address name, e.g. rth-fuse-space.my-queue
  spec:
    address: accountQueue
    # AMQ address name
    plan: brokered-queue
    # AMQ Online address plan name, e.g. 'brokered-queue'
    type: queue
    # AMQ Online address type for the address plan, e.g. 'queue'
# Multiple addresses can be specified in this List
# BEGIN EXCLUDE
- apiVersion: enmasse.io/v1alpha1
  kind: Address
  metadata:
    name: user1-fuse-space.account-queue
  spec:
    address: accountQueue
    plan: brokered-queue
    type: queue
- apiVersion: enmasse.io/v1alpha1
  kind: Address
  metadata:
    name: user1-fuse-space.input-queue
  spec:
    address: inputQueue
    plan: brokered-queue
    type: queue
- apiVersion: enmasse.io/v1alpha1
  kind: Address
  metadata:
    name: user1-fuse-space.error-notification
  spec:
    address: errorNotification
    plan: brokered-topic
    type: topic
# END EXCLUDE
